services:
  web:
    image: nginx
    container_name: goaccess_nginx
    ports:
      - 9080:80
    volumes:
      - ./web-logs:/var/log/nginx
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html

  goaccess_default:
    image: eitch/docker-goaccess
    container_name: goaccess_default
    volumes:
      - ./goaccess_start_default.sh:/usr/local/bin/goaccess_start.sh:ro
      - ./configs/goaccess.default.conf:/srv/config/goaccess.conf:ro
      - ./logs:/srv/logs:ro
      - ./public:/srv/report
    command: ["--no-global-config", "--config-file=/srv/config/goaccess.conf"]
    restart: unless-stopped

  goaccess_proxy:
    image: eitch/docker-goaccess
    container_name: goaccess_proxy
    volumes:
      - ./goaccess_start_proxy.sh:/usr/local/bin/goaccess_start.sh:ro
      - ./configs/goaccess.proxy.conf:/srv/config/goaccess.conf:ro
      - ./logs:/srv/logs:ro
      - ./public:/srv/report
    entrypoint: /bin/sh
    command: /usr/local/bin/goaccess_start.sh
    restart: unless-stopped

