services:
  goaccess:
    image: eitch/docker-goaccess
    container_name: goaccess
    ports:
      - "7889:7889"
    volumes:
      - ./goaccess.conf:/config/goaccess.conf:ro
      - ./logs:/srv/logs:ro
      - ./public:/srv/report
    restart: unless-stopped
